# local model parameter variables
from Models.Training_parameters.adult import *
from Models.Training_parameters.aquatic_toxicity import *
from Models.Training_parameters.bike_sharing import *
from Models.Training_parameters.breast_cancer import *
from Models.Training_parameters.compressive_strength import *
from Models.Training_parameters.credit_default import *
from Models.Training_parameters.crime_predict import *
from Models.Training_parameters.diabetic_retinopathy import *
from Models.Training_parameters.facebook_metrics import *
from Models.Training_parameters.german_credit import *
from Models.Training_parameters.seismic_bumps import *
from Models.Training_parameters.sgemm_gpu import *
from Models.Training_parameters.student_performance_mat import *
from Models.Training_parameters.student_performance_por import *
from Models.Training_parameters.thoracic_surgery import *
from Models.Training_parameters.wine_quality_red import *
from Models.Training_parameters.wine_quality_white import *
from Models.Training_parameters.yeast import *
